{
 "title": "ahoyDTU",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "site",
    "query": {
     "query": "label_values(ahoy_solar_inverter_info,site)"
    }
   },
   {
    "name": "inverter",
    "query": {
     "query": "label_values(ahoy_solar_inverter_info{site=~\"$site\"},name)"
    }
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(ahoy_solar_P_DC_watt{site=~\"$site\", inverter=~\"$inverter\"},channel)"
    }
   },
   { "name": "price", "label": "Preis / kWh", "query": "0.36" }
  ]
 },
 "panels": [
  { "title": "General stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PF_AC",
   "type": "stat",
   "description": "Power Factor",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_PF_AC{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ALARM_MES_ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_ALARM_MES_ID{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LastAlarmCode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_LastAlarmCode{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Q_AC_var",
   "type": "stat",
   "description": "Reactive Power",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_Q_AC_var{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temp_celsius",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_Temp_celsius{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "freeheap",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_freeheap{site=~\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_info{site=~\"$site\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "inverter_info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_inverter_info{site=~\"$site\",name=~\"$inverter\"}",
     "legendFormat": "{{name}} {{serial}}"
    }
   ]
  },
  {
   "title": "inverter_is_available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_inverter_is_available{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inverter_is_enabled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_inverter_is_enabled{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inverter_is_producing",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_inverter_is_producing{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_uptime{site=~\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P_AC_watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ahoy_solar_P_AC_watt{site=~\"$site\",inverter=~\"$inverter\"}",
     "legendFormat": "{{site}}:{{inverter}}"
    },
    {
     "expr": "max_over_time(ahoy_solar_P_AC_watt{site=~\"$site\",inverter=~\"$inverter\"}[31d])",
     "legendFormat": "MAX"
    },
    {
     "expr": "avg_over_time(ahoy_solar_P_AC_watt{site=~\"$site\",inverter=~\"$inverter\"}[31d])",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "P_DC_watt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_P_DC_watt{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  {
   "title": "Irradiation_ratio ($channel)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "repeat": "channel",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_Irradiation_ratio{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  { "title": "Yield - Ertrag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "YieldDay_wattHours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldDay_wattHours{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  {
   "title": "YieldTotal_kilowattHours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldTotal_kilowattHours{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  {
   "title": "YieldDay_wattHours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldDay_wattHours{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  {
   "title": "YieldTotal_kilowattHours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldTotal_kilowattHours{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  {
   "title": "Yield / Day in EUR",
   "type": "barchart",
   "description": "Not really Yield, for not it's just the money I didn't have to spend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldDay_wattHours{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"} / 1000 * $price",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  {
   "title": "Yield TOTAL in EUR",
   "type": "barchart",
   "description": "Not really Yield, for not it's just the money I didn't have to spend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldTotal_kilowattHours{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"} * $price",
     "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
    }
   ]
  },
  {
   "title": "DC - Direct Current - Gleichstrom - PV-Modules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "P_DC_watt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ahoy_solar_P_DC_watt{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
       "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
      }
     ]
    },
    {
     "title": "Irradiation_ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ahoy_solar_Irradiation_ratio{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
       "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
      }
     ]
    },
    {
     "title": "U_DC_volt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "ahoy_solar_U_DC_volt{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
       "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
      }
     ]
    },
    {
     "title": "I_DC_ampere",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ahoy_solar_I_DC_ampere{site=~\"$site\",inverter=~\"$inverter\",channel=~\"$channel\"}",
       "legendFormat": "{{site}}:{{inverter}}:{{channel}}"
      }
     ]
    },
    {
     "title": "Efficiency_ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ahoy_solar_Efficiency_ratio{site=~\"$site\",inverter=~\"$inverter\"}",
       "legendFormat": "{{site}}:{{inverter}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AC - Alternating Current - Wechselstrom - Netzstrom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "F_AC_hertz",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "ahoy_solar_F_AC_hertz{site=~\"$site\",inverter=~\"$inverter\"}",
       "legendFormat": "{{site}}:{{inverter}}"
      }
     ]
    },
    {
     "title": "P_AC_watt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ahoy_solar_P_AC_watt{site=~\"$site\",inverter=~\"$inverter\"}",
       "legendFormat": "{{site}}:{{inverter}}"
      }
     ]
    },
    {
     "title": "U_AC_volt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "ahoy_solar_U_AC_volt{site=~\"$site\",inverter=~\"$inverter\"}",
       "legendFormat": "{{site}}:{{inverter}}"
      }
     ]
    },
    {
     "title": "I_AC_ampere",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ahoy_solar_I_AC_ampere{site=~\"$site\",inverter=~\"$inverter\"}",
       "legendFormat": "{{site}}:{{inverter}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Radiosignal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Radio Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "irate(ahoy_solar_radio_frame_cnt{site=~\"$site\"}[5m])",
       "legendFormat": "frame_cnt"
      },
      {
       "expr": "irate(ahoy_solar_radio_retrans_cnt{site=~\"$site\"}[5m])",
       "legendFormat": "retrans_cnt"
      },
      {
       "expr": "irate(ahoy_solar_radio_rx_fail{site=~\"$site\"}[5m])",
       "legendFormat": "rx_fail"
      },
      {
       "expr": "irate(ahoy_solar_radio_rx_fail_answer{site=~\"$site\"}[5m])",
       "legendFormat": "rx_fail_answer"
      },
      {
       "expr": "irate(ahoy_solar_radio_rx_success{site=~\"$site\"}[5m])",
       "legendFormat": "rx_success"
      },
      {
       "expr": "irate(ahoy_solar_radio_tx_cnt{site=~\"$site\"}[5m])",
       "legendFormat": "tx_cnt"
      }
     ]
    },
    {
     "title": "Radio Signal",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "ahoy_solar_wifi_rssi_db{site=~\"$site\"}",
       "legendFormat": "{{devicename}}"
      }
     ]
    }
   ]
  }
 ]
}